CREATE TABLE Person(
                       person_id int GENERATED BY DEFAULT AS IDENTITY UNIQUE,
                       full_name VARCHAR UNIQUE,
                       year_of_birth int
);

INSERT INTO Person (full_name, year_of_birth)
VALUES ('Иванов Иван Иванович', 1970),
       ('Алексеев Алексей Алексеевич', 1989),
       ('Петров Пётр Петрович', 1960),
       ('Путин Владимир Владимирович', 1952),
       ('Фёдоров Мирон Янович', 1985);

SELECT * FROM Person;
DROP TABLE Person;

CREATE TABLE Book(
                     book_id int GENERATED BY DEFAULT AS IDENTITY,
                     person_id int REFERENCES Person(person_id) ON DELETE SET NULL DEFAULT NULL,
                     title varchar,
                     author varchar,
                     year int
);

INSERT INTO Book (title, author, year)
VALUES ('День опричника', 'Владимир Сорокин', 2006),
       ('Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018),
       ('Философия Java', 'Брюс Эккель', 2018),
       ('Игра в бисер', 'Герман Гессе', 1943),
       ('Бытие и время', 'Мартин Хайдеггер', 1927),
       ('Над пропастью во ржи', 'Джером Сэлинджер', 1951),
       ('Психология обыденной жизни', 'Фрейд Зигмунд', 1904);


SELECT * FROM Book;
DROP TABLE Book;

SELECT * FROM Person WHERE person_id=1;